application: avisaenchente
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: main.application
  secure: always

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
- name: endpoints
  version: 1.0

